version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1026:1026"
  proxy:
    image: nginx:1.27.5
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/templates
    environment:
      - BACKEND_HOST=${SERVER_HOST}