export const pieceWidth = 100
export const pieceHeight = 20
export const sideWidth = 50
export const gapWidth = 10
export const frameWidth = 10
export const boardHeight = 1120
export const standHeight = 140
export const storeHeight = pieceHeight * 15
export const triangleHeight = 400
export const middleX = sideWidth + pieceWidth + sideWidth + 6 * pieceWidth + sideWidth + gapWidth / 2
export const boardWidth = middleX * 2
export const svgOriginX = 0
export const svgOriginY = 0
export const triangleTriggerHeight = triangleHeight + pieceWidth / 2
